"""Updated events and user models

Revision ID: ed7710da19d9
Revises: e4d7ee46e255
Create Date: 2023-09-28 15:54:57.443113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed7710da19d9'
down_revision = 'e4d7ee46e255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_events_ibfk_1', 'user_events', type_='foreignkey')
    op.drop_column('user_events', 'event_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_events', sa.Column('event_id', mysql.VARCHAR(length=255), nullable=False))
    op.create_foreign_key('user_events_ibfk_1', 'user_events', 'events', ['event_id'], ['event_id'])
    # ### end Alembic commands ###
